"""add capital asset fields

Revision ID: add_capital_asset_fields
Revises: e640d15a519e
Create Date: 2025-10-07 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_capital_asset_fields'
down_revision = 'e640d15a519e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capital_assets', sa.Column('asset_name', sa.String(length=255), nullable=True))
    op.add_column('capital_assets', sa.Column('monthly_income', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('capital_assets', sa.Column('rental_income', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('capital_assets', sa.Column('monthly_rental_income', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capital_assets', 'monthly_rental_income')
    op.drop_column('capital_assets', 'rental_income')
    op.drop_column('capital_assets', 'monthly_income')
    op.drop_column('capital_assets', 'asset_name')
    # ### end Alembic commands ###
