from __future__ import annotations

from .legacy_loader import load_legacy_steps_module


def _run_orchestration(
    *,
    request,
    db,
    messages,
    request_id: str,
    original_user_msg: str | None,
    current_pension_portfolio,
    is_qa_mode: bool,
    no_tools_requested: bool,
    is_doc_request: bool,
    is_cashflow_request: bool,
    is_comparison_request: bool,
    is_net_request: bool,
    is_portfolio_analysis: bool,
    analysis_default_retirement_age,
    force_max_exemption: bool,
    wants_ignore_blocked: bool,
    explicit_termination: bool,
    termination_change: bool,
    termination_already_executed: bool,
    wants_execute_target_plan: bool,
    wants_fixation_execute: bool,
    logger,
    computed_data,
    log_llm_event_fn,
):
    legacy_module = load_legacy_steps_module()
    return legacy_module._run_orchestration(
        request=request,
        db=db,
        messages=messages,
        request_id=request_id,
        original_user_msg=original_user_msg,
        current_pension_portfolio=current_pension_portfolio,
        is_qa_mode=is_qa_mode,
        no_tools_requested=no_tools_requested,
        is_doc_request=is_doc_request,
        is_cashflow_request=is_cashflow_request,
        is_comparison_request=is_comparison_request,
        is_net_request=is_net_request,
        is_portfolio_analysis=is_portfolio_analysis,
        analysis_default_retirement_age=analysis_default_retirement_age,
        force_max_exemption=force_max_exemption,
        wants_ignore_blocked=wants_ignore_blocked,
        explicit_termination=explicit_termination,
        termination_change=termination_change,
        termination_already_executed=termination_already_executed,
        wants_execute_target_plan=wants_execute_target_plan,
        wants_fixation_execute=wants_fixation_execute,
        logger=logger,
        computed_data=computed_data,
        log_llm_event_fn=log_llm_event_fn,
    )
