# קונפיגורציה לגילאי זכאות לקיבוע זכויות
# ניתן לעדכן ערכים אלו בעתיד ללא שינוי קוד

current_age_male: 67
current_age_female: 62

# הערות:
# - גילאי הזכאות עשויים להשתנות בעתיד בהתאם לחקיקה
# - המערכת תטען ערכים אלו בעדיפות על פני הקבועים בקוד
# - במקרה של כשל בטעינת הקונפיג, המערכת תשתמש בברירות המחדל בקוד
